### ISSUE TITLE
[MLS Spec change] Implement GREASE support (1/2, Receiving).

### ISSUE THREAD

**Issue by duesee** [openmls/openmls#1337]
In order to interoperate with other implementations, OpenMLS needs to GREASE. (See https://www.ietf.org/archive/id/draft-ietf-mls-protocol-20.html#section-13.5.)

# TODO

* [ ] LeafNode.capabilities.ciphersuites
* [ ] LeafNode.capabilities.extensions
* [ ] LeafNode.capabilities.proposals
* [ ] LeafNode.capabilities.credentials
* [ ] LeafNode.extensions
* [ ] KeyPackage.extensions
* [ ] GroupInfo.extensions

# Related

* [ ] #1311 

It might be worth it to already implement this in `tls_codec`.

**Comment by duesee** [comment]
I already implemented support for unknown types and extensions during interop. However, in order to be a good Internet citizen, OpenMLS should not only accept unknown values but GREASE itself. I propose to split this issue to track GREASE-receive and GREASE-send.
