### ISSUE TITLE
[Meta] Storage

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#1510]
This issue tracks other issues related to storage refactoring:

 - [x] https://github.com/openmls/openmls/issues/1509
 - [x] https://github.com/openmls/openmls/issues/672
 - [x] https://github.com/openmls/openmls/issues/1194 (turn into actionable issue or close)
 - [x] https://github.com/openmls/openmls/issues/1355 (turn into actionable issue or close)
 - [x] https://github.com/openmls/openmls/issues/337 (turn into actionable issue or close)
 - [x] https://github.com/openmls/openmls/issues/1511
 - [x] https://github.com/openmls/openmls/issues/1518
 - [x] #1544

**Comment by keks** [comment]
What is the status of the two closed, but not checked issues? Can we check then?

**Comment by franziskuskiefer** [comment]
Yes, I think and did so.

**Comment by keks** [comment]
I think we can close this as completed.
