### ISSUE TITLE
[Meta] Stable Storage Tracking Issue

### ISSUE THREAD

**Issue by keks** [openmls/openmls#1564]
- [x] First Implementation (#1562 )
- [ ] Add comments and documentation
- [x] Use constants instead of literals as versions
- [ ] Support storing more parts of the state
  - [ ] Items from the Key Store (deleting key package should also delete secrets, see note on hierarchical deletion)
  - [ ] Items that live in `CoreGroup`
    - [ ] GroupEpochSecrets
    - [ ] own leaf index
    - [ ] use ratchet tree extension
    - [ ] MessageSecretsStore (see note below)
    - [ ] ResumptionPskStore
  - [ ] Items that live in `MlsGroup`
    - [ ] JoinConfig
    - [ ] ProposalStore
      - [x] append
      - [x] query proposal
      - [x] query proposal list
      - [x] ~~is_empty~~
        - not needed, since answering that query requires fetching and parsing the list anyway. Just query the list and call is_empty on that
      - [ ] clear proposal queue
    - [ ] own leaf nodes
    - [ ] aad
    - [ ] MlsGroupState, incl. PendingCommitState
    - [x] ~~InnerState~~
      - can be removed, because we just persist everything immediately
- [ ] load PublicGroup from storage
- [ ] load CoreGroup from storage
- [ ] load MlsGroup from storage
- [ ] Review group storage granularity
- [ ] #1575

**Note on hierarchical deletion**: There are cases where removing one entry implies removing other ones, and which ones are to be removed follows from the contents of the first entry. For example, when removing a `KeyPackage`, it would be nice if we also removed the respective secrets.
However, the storage layer mostly sees the serialized data. One way this could be done is to add methods on the deleted entity to retrieve the storage keys to the transitive deletes that have to be deleted.

**Comment by franziskuskiefer** [comment]
First PR to get in #1565

**Comment by franziskuskiefer** [comment]
@keks can you update this and clearly list all open issues and file follow ups where necessary?

**Comment by keks** [comment]
I initially started working on #1562, but it turned out that the approach to duplicate all the types of a foreign crate made it impossible to keep the approach we use for using types to indicate validated values.

In #1565 we merged an implementation of a more pragmatic approach, which kept the serialization inside the openmls crate. This is theoretically a little more fragile, but at least it is possible, and the fragility can be caught with tests.

In #1579 @franziskuskiefer added some fixes for a method that @kkohbrok eventuallly noticed was duplicate, so we removed it in #1591.
