### ISSUE TITLE
v0.4 Documentation

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#598]
[v0.4](https://github.com/openmls/openmls/milestone/3) will be the first release of OpenMLS with a somewhat stable API that is supposed to be used in other projects. While we still expect many changes after this release it will allow us to collect feedback on the API and OpenMLS in general.

This issue tracks documenting the v0.4 release

- [x] v0.4 release notes #741 
- [x] v0.4 discussion page(s) (part of release process)
- [x] #779
- [x] Usage examples/tutorials for the group API in the book
- [x] Rustdoc for other public APIs
  - [x] #769
  - [x] #770
  - [x] #771
  - [x] #772
  - [x] #773
  - [x] #774
  - [x] #775
  - [x] #776
- [x] Usage examples/tutorials for other public APIs in the book
  - [x] #794
  - [x] #795
- [x] #568
