### ISSUE TITLE
Tracking dependencies for v0.4

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/openmls#599]
OpenMLS has a bunch of dependencies that need proper/new releases before [v0.4](https://github.com/openmls/openmls/milestone/3) can be released.

- [ ] [openmls_traits](https://github.com/openmls/openmls/tree/main/traits)
  - [ ] #701 
- [ ] [memory_keystore](https://github.com/openmls/openmls/tree/main/memory_keystore)
  - [x] #656 
- [ ] [evercrypt_backend](https://github.com/openmls/openmls/tree/main/evercrypt_backend)
- [ ] [openmls_rust_crypto](https://github.com/openmls/openmls/tree/main/openmls_rust_crypto)
  - [ ] [rust_crypto](https://github.com/openmls/openmls/tree/main/rust_crypto)
- [x] [hpke-rs](https://github.com/franziskuskiefer/hpke-rs) (@franziskuskiefer) #766 
- [x] [tls_codec](https://github.com/RustCrypto/formats/tree/master/tls_codec) (@franziskuskiefer) #766

**Comment by franziskuskiefer** [comment]
External dependencies have been released and all crates in this repository have pre-release versions.
