### ISSUE TITLE
[Meta] External Init

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#630]
This issue tracks the progress on the "External Init" functionality via external commits: https://messaginglayersecurity.rocks/mls-protocol/draft-ietf-mls-protocol.html#section-11.2.1.

- [x] Constructors for `NewMember` commits, proposals and MLSPlaintexts
- [x] one-shot HPKE functions for setup and key export by sender and receiver
- [x] creation of external init commits
- [x] application/processing of external init commits (`new_from_external_init`) by others
- [x] application/processing of external init commits (`new_from_external_init`) by the creator
- [x] #682
- [x] #680
- [x] #681

TODO: There are a number of spec-change issues that might be fixed by this. Before closing this issue, please check the following issues.
- [x] #556
- [x] #542
- [x] #536
- [x] #289
- [x] #286
- [x] #192

**Comment by raphaelrobert** [comment]
All checks completed, closing this.
