### ISSUE TITLE
[Meta] Refactor CoreGroup/Internal structure

### ISSUE THREAD

**Issue by raphaelrobert** [openmls/openmls#691]
- [ ] Identify tests for `CoreGroup` that are no longer needed and delete them
 - [ ] Remove the `test-utils` feature, introduce `interop-client` feature instead and only expose where needed
 - [ ] #645 
 - [ ] Remove the config of `CoreGroup`
 - [ ] Merge `CoreGroup` with `MlsGroup`, possibly by making it a submodule of the latter

**Comment by kkohbrok** [comment]
I'm not sure it's a good idea to merge `CoreGroup` with `MlsGroup`. I think `CoreGroup` marks a good boundary of what's in the spec vs. what OpenMLS does on top of that.

**Comment by raphaelrobert** [comment]
I think this is already covered enough by #645 and #739.
