### ISSUE TITLE
[Meta] Tree Validation

### ISSUE THREAD

**Issue by kkohbrok** [openmls/openmls#807]
This ticket tracks other tickets related to the validation of trees that the client receives. 

- [ ] create list of tree validation steps
- [ ] #800 
- [ ] parent hash validation (documentation and testing)
- [ ] node validation (only keypackages in leaves, only parent nodes in non-leaves)

**Comment by keks** [comment]
Looks like the dashboard is missing the validation checks for incoming welcome messages, so I opened [an issue for that](https://github.com/openmls/validation.dhall/issues/22). I couldn't easily find anything in the RFC - Do we need to check the validity of a ratchet tree anywhere other than when we join a group?
